### PR TITLE
feat(wrapper): upgrade PointSDK

### PR DESCRIPTION
**Pull request by poborin**

### CODE REVIEW

**Comment by jsprincep** [comment]
@poborin because the sdk is included as a raw aar, instead of a maven dependency, we need to update the dependencies manually for the Xamarin wrapper.

Looking at the diff, it would appear we need should only need to update the work-runtime: https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime/ and https://www.nuget.org/packages/Xamarin.AndroidX.Work.Work.Runtime.Ktx/ nuget packages to 2.7.0.

Let us know if you need assistance with this.

**Comment by poborin** [comment]
yeah, I updated them through the NuGet package manager and it had to update a few other dependencies. Please don't be overwhelmed by the changes.

**Comment by jsprincep** [comment]
@poborin I'm still getting the version number as 15.3.5 after clearing the packages and reinstalled. Where did you get the aar from?

**Review by jsprincep — APPROVED** [review]
Got there in the end 😅

**Pull request merged**
